// components/RootLayout.tsx
import type { Metadata } from 'next';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import Nav from '../components/navbar';
import Footer from '@/components/footer';
import '../style/globals.css';
import '../style/swiffy-slider.css';
import 'bootstrap/dist/css/bootstrap.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html>
      <Head>
        <title>Derived</title>
        <meta name="description" content="Generated by create next app" />
         <link
            href="https://swiffyslider.com/configuration/?slider-item-reveal=slider-item-reveal&slider-item-nosnap-touch=slider-item-nosnap-touch&slider-nav-style=slider-nav-round&slider-nav-visible=slider-nav-visible&slider-nav-page=slider-nav-page&slider-indicators-outside=slider-indicators-outside&slider-indicators-sm=slider-indicators-sm&slider-item-helper=slider-item-helper"
            rel="stylesheet"
            crossOrigin="anonymous"
          />
          <script
            src="https://cdn.jsdelivr.net/npm/swiffy-slider@1.6.0/dist/js/swiffy-slider.min.js"
            crossOrigin="anonymous"
            defer
          ></script>
      </Head>
      <body>
      <div className="container-fluid px-0">
        <Nav />
        {children}
        <Footer />
      </div>
      </body>
      </html>
    
  );
}
