
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../style/globals.css";
import 'bootstrap/dist/css/bootstrap.css';
const inter = Inter({ subsets: ["latin"] });
import Nav from "../components/navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
      <div className="container-fluid">
        <Nav/>
        {children}
        </div></body>
    </html>
  );
}
